---
version: "3.8"

services:
  backend-dev:
    build: .
    command: yarn run start:dev
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/carly
    ports:
      - "8000:8000"
    volumes:
      - ./prisma/carly.db:/usr/src/carly/prisma/carly.db
      - ./static:/usr/src/carly/static